package org.app.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor // Lombok generates a no-argument constructor
@AllArgsConstructor // Lombok generates an all-argument constructor
public class PaymentDTO {

    private Long id;         // The ID field (auto-generated by DB)
    private Long subscriptionId;
    private double amount;

    // Custom constructor without 'id' field (id will be handled by the database)
    public PaymentDTO(Long subscriptionId, double amount) {
        this.subscriptionId = subscriptionId;
        this.amount = amount;
    }
}
