package org.app.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor // Lombok generates a no-argument constructor
@AllArgsConstructor // Lombok generates an all-argument constructor
public class SubscriptionDTO {

    private Long id;              // The ID field (auto-generated by DB)
    private Long userId;
    private Long publicationId;
    private int months;

    // Custom constructor without 'id' field (id will be handled by the database)
    public SubscriptionDTO(Long publicationId, int months) {
        this.publicationId = publicationId;
        this.months = months;
    }
}
